apiVersion: v1
kind: Service
metadata:
  name: pma
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: pma
spec:
  ports:
    - name: pma
      port: 5000          # - port exposed internally in the cluster
      targetPort: 5000    # - the container port to send requests to
  selector:
    app: pma
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: pma
spec:
  selector:
    matchLabels:
      app: pma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - image: pma
        name: pma
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: pma